name: Test Project

# trigger
on: push

#work to be done
jobs:

  test:
  
    #define the runner (environment) we want to run this guy on
    runs-on: ubuntu-latest
    
    steps:
    
      # - name: PrintEnvironmentVariables
      #   run: |
      #     echo "Environement Vars"
      #     echo $GITHUB_WORKSPACE

      - name: Get Code
        uses: actions/checkout@v3

