name: Test Project

# trigger
on: push

#work to be done
jobs:

  test:
  
    #define the runner (environment) we want to run this guy on
    runs-on: ubuntu-latest
    
    steps:
    
      # - name: PrintEnvironmentVariables
      #   run: |
      #     echo "Environement Vars" 
      #     echo $GITHUB_WORKSPACE

      # download the code to the runner env
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      
      - name: Install Dependencies
        run: npm ci 

      - name: Run Tests
        run: npm test



        

